### ISSUE TITLE
DLL errors

### ISSUE THREAD

**Issue by Neilt100** [mullenkamp/hilltop-py#1]
Hi,

hilltop-py is a great idea.  Thanks for putting it together. We've recently purchased a subscription to Hilltop, but the python scripting doesn't seem to work.  I have installed hilltop-py through pip, and can import hilltop.  However, I get an error message:

`ImportError: DLL load failed: The specified module could not be found`

when Hilltop is imported.  The path to the Hilltop.pyd file correctly specified in the PYTHONPATH and I have run the installation in Hilltop Manager.

Are there any particular DLLs the Hilltop.pyd requires?  I have also installed pywin32.

Thanks,

Neil

**Comment by mullenkamp** [comment]
Hi Neil,

Thanks for trying it out.
A couple things could be the issue. 
If you are running a 64bit python and the path to the Hilltop.pyd is the 32bit version, you will get this message. In the root Hilltop directory, there should be a folder called x64, which contains the 64bit versions of Hilltop.
Although from my experience, this new Hilltop.pyd can be a bit buggy...it's still quite a work in progress by Mark R.

Give the COM module a try:
https://hilltop-py.readthedocs.io/en/latest/usage.html#com-module

From my testing, it's more reliable and has a bit more functionality as well. Just make sure you follow the setup procedure in the docs.

Also, are you at a council? If so, you might already have a web service setup with Hilltop. In which case you can simply use the web service module:
https://hilltop-py.readthedocs.io/en/latest/usage.html#web-service

Let me know how it goes.

**Comment by Neilt100** [comment]
Hi,

Thanks- I've followed the setup procedure in the doc and tried the COM module, but get an error:

`Could not located a type library matching 'Hilltop Data Access'`

Any suggestions are welcome!  I will also contact Mark Rodgers to see if there is a file we're missing. We're not from a council, so we don't have a webservice set up.

Cheers,

Neil

**Comment by mullenkamp** [comment]
You get that error even after running the following?:
```
from hilltoppy import com

com.makepy_hilltop()
```

**Comment by Neilt100** [comment]
Yes- `from hilltoppy import com` generates no errors, but `com.makepy_hilltop()` does generate the error.

**Comment by mullenkamp** [comment]
well...that error would indicate to me that the windows registry step wasn't performed properly:
https://hilltop-py.readthedocs.io/en/latest/usage.html#register-hydrolib

It looks like I left out the requirement that you need to run Manager.exe as administrator. Then go to "Configure" > "Installation". That should tell windows about the 'Hilltop Data Access'. 
I'll edit the docs to make that explicit.
Try that out.

**Comment by mullenkamp** [comment]
I'll close this issue for now. If you still have the problem, open it back up.
