### ISSUE TITLE
Unable to access Stage [Gauging Results]

### ISSUE THREAD

**Issue by jeffcnz** [mullenkamp/hilltop-py#22]
https://data.hbrc.govt.nz/EnviroData/ContinuousArchive.hts?service=Hilltop&request=MeasurementList&Site=Tutaekuri%20River%20at%20Puketapu%20HBRC%20Site has the Gauging Results Stage measurement needing to be requested as Stage [Gauging Results], but this is not in the gauging_dict in web_services.py so an error is passed.

Adding and extra row to the dictionary (line 24) fixes the issue. Row id

 'Stage [Gauging Results]': {'row': 'I1', 'multiplier': 0.001}, 

Note: there is a problem accessing Gauging Results from this server so it may be hard to test

**Comment by jeffcnz** [comment]
The multiplier seems to be converting the results to meters from mm, but the units of measure don't come through.  It would be good to have the units for each value so that conversions can be done if required.  Some stage measurements are in m and some are in mm.  Units are usually in the datasource results, but for gaugings these might need to be specified as part of the dictionary.

**Comment by mullenkamp** [comment]
> The multiplier seems to be converting the results to meters from mm, but the units of measure don't come through. It would be good to have the units for each value so that conversions can be done if required. Some stage measurements are in m and some are in mm. Units are usually in the datasource results, but for gaugings these might need to be specified as part of the dictionary.

Dealing with units properly is certainly something I've been wanting to do, but it's not a trival task.
[Pint](https://pint.readthedocs.io/en/stable/) deals with units nicely and I would like to implement this at some point. So that users can simply ask for specific units or have default units for particular measurement types.

**Comment by mullenkamp** [comment]
I'll implement the easy fix that you mentioned, and I'll add a new issue about better handling and conversion of units.
Thanks!

**Comment by mullenkamp** [comment]
Just to clarify something...I only implemented that gauging_dict multiplier because the values returned by the gauging results are always as integers and in some cases need to be converted to an appropriate unit. I should really just use the divisor values for conversion...
