### ISSUE TITLE
Return units with results

### ISSUE THREAD

**Issue by jeffcnz** [mullenkamp/hilltop-py#23]
Units aren't currently returned with the measurement results.  They are available in the DataSource header information.  Adding a units column to the returned dataframe would allow the measurement units to be viewed and compared, and conversions scripted if required.  Gauging results would need to have the units hard coded into the dictionary.

**Comment by mullenkamp** [comment]
A Units column is returned via the measurement_list function. Correct me if I'm wrong, but the units do not vary with time? They should only vary by site and measurement type?
As long as the units do not vary with time, then units do not need to be returned via the get_data function.
This is all referring to the web_service module by the way.

**Comment by jeffcnz** [comment]
Agree that the units don't vary with time, but they are within the data returned by a GetData request, as are the measurement and the site.  Measurement and Site are included in the dataframe, and it would be useful to include the units in the dataframe as well, preventing the need for a seperate request to get data that is in the payload from a GetData request.

**Comment by mullenkamp** [comment]
I've now covered this in issue #28
