### ISSUE TITLE
Element tree error when running Python 3.9

### ISSUE THREAD

**Issue by jeffcnz** [mullenkamp/hilltop-py#5]
Error when trying to use Webserver version with Python 3.9

ElementTree.Element.getchildren depreciated from Python 3.2

https://docs.python.org/3.8/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element.getchildren

the source is In webserver line 158  

```
children = s.getchildren
```

replacing with 

```
children = list(s) 
```

fixes, but may need try catch to try and ensure backward compatibility

**Comment by mullenkamp** [comment]
Thanks for finding that and for providing an easy fix.
I'll make that fix and ensure backwards compatibility back to version 3.6 (at least).

**Comment by mullenkamp** [comment]
The fix has been made. Version 1.4.7 contains the new fixes.
I've also updated the CI testing processes from Travis CI to Github Actions and tests the package using Python 3.6-3.9.
Thanks again for reporting the problem.
