### ISSUE TITLE
pandas date parsing warning

### ISSUE THREAD

**Issue by mwtoews** [mullenkamp/hilltop-py#70]
With the latest master (df3d747f8a93072317ffa255bf76cea8ff4c319d), I'm seeing many repetitive warning messages:
> d:\src\hilltop-py\hilltoppy\utils.py:193: UserWarning: Parsing dates in %Y-%m-%dT%H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  val = pd.to_datetime(val, dayfirst=True)

Shouldn't `dayfirst=False` since `hilltoppy.web_service.get_data` specifies a "format 2001-01-01"?

**Comment by mullenkamp** [comment]
Fixed as per your suggestion in #72
