### ISSUE TITLE
Measurement list does not return dict

### ISSUE THREAD

**Issue by Sirvine1994** [mullenkamp/hilltop-py#74]
The inputs of the function `measurement_list `are given by:

`def measurement_list(base_url, hts, site, measurement=None, output='dataframe', timeout=60, **kwargs):`

The doc string says the following about the `output` parameter:

`output : dataframe or list of dict
        The output object. Must be either dataframe or list of dict.`

However, the output variable is not used in the `measurement_list` function and the function always returns a dataframe.

Simple script to reproduce:
```
from hilltoppy import web_service as ws

base_url = "http://hilltop.gw.govt.nz/"
hts = "data.hts"
site = "Akatarawa River at Hutt Confluence"
print(
    type(
        ws.measurement_list(
            base_url,
            hts,
            site,
            output="dict",
        )
    )
)
```
This script should return a list of dictionaries, but instead returns a pandas dataframe

The function `get_data` attempts to using this functionality as a backup way of obtaining the measurement desired. The following code throws an error when the if loop is entered:

```
if 'Item' not in ds_dict1:
    ml = measurement_list(base_url, hts, site, measurement=measurement, output='dict', timeout=timeout)
    for m in ml:
        if m['MeasurementName'].lower() == measurement.lower():
            ds_dict1.update(m)
```

**Comment by mullenkamp** [comment]
Hi Sam,
My apologies...that output keyword must be a legacy parameter, because it doesn't do anything in the function. I can easily make it work again if you like, but keep in mind that the get_data function does not have this option. 
From your email you sent me, I don't think this will ultimately help you with your problem.
I'll reply to your email to see if we can chat about it.

**Comment by mullenkamp** [comment]
Removed the output parameter in #94
