### ISSUE TITLE
Unable to read check data

### ISSUE THREAD

**Issue by Sirvine1994** [mullenkamp/hilltop-py#84]
When the measurement name is different than the data source name, the get_data function fails to find the data. This is always the case for check data.

An example snippet of xml data returned by Hilltop is:
<DataSource Name="Water Temperature" NumItems="3">
<TSType>CheckSeries</TSType>
…
<ItemName>Water Temperature Check</ItemName>

Here ItemName is not the same as the DataSource name. In the get_data function, this section looks for the ItemName which matches the data source:

        for m in measurements:
            m_dict = {c.tag: convert_value(c.text) for c in m}
            m_name = m_dict.pop('ItemName')

            if measurement.lower() == m_name.lower():

However, if the ItemName (measurement name) and the data source (the input) do not match, this fails. For data which has a different measurement name than the data source name (which is always the case for check data AFAIK) multiple inputs are required. In the above example, the Hilltop call requires 'Water temperature' in the server call, but for the processing it needs to match ‘Water Temperature Check’ and not ‘Water Temperature’.

**Comment by mullenkamp** [comment]
The new Hilltop class seems to be able to handle check data except when the hts only has check data...which should be super rare.
